# numpy Library
** Processing N-Dimensional arrays**


In [14]:
a=253
b=253
print(id(a))
print(id(b))

140710110802624
140710110802624


In [3]:
import numpy as np
li=[1,2,34,'s']
a=np.array(li)
a

array(['1', '2', '34', 's'], dtype='<U11')

In [6]:
import numpy as np
li=[1,2,34,'s']
a=np.array(li)
b=np.arange(15)
b
print(a)
print(b)

['1' '2' '34' 's']
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
rn=np.random.randint(1,100)

In [11]:
rn

75

In [23]:
rnn=np.random.randint(0,2,size=(3,3,3,3))
rnn[2][2][2][1]

1

In [25]:
rnn

array([[[[1, 0, 0],
         [0, 0, 0],
         [0, 1, 0]],

        [[1, 0, 0],
         [1, 1, 1],
         [0, 1, 1]],

        [[0, 1, 0],
         [1, 1, 0],
         [1, 0, 0]]],


       [[[0, 1, 1],
         [1, 0, 1],
         [0, 1, 1]],

        [[1, 1, 1],
         [1, 0, 1],
         [1, 0, 1]],

        [[0, 0, 0],
         [1, 1, 0],
         [1, 0, 1]]],


       [[[1, 1, 1],
         [1, 1, 0],
         [1, 0, 0]],

        [[0, 1, 1],
         [0, 1, 0],
         [0, 1, 0]],

        [[0, 0, 1],
         [0, 0, 0],
         [0, 1, 0]]]])

In [24]:
rnn.ndim#dimensions

4

In [26]:
rnn.size#size

81

In [27]:
rnn.shape#shape

(3, 3, 3, 3)

In [29]:
rnn.itemsize

4

In [30]:
rnn.nbytes

324

In [34]:
r=np.random.randint(0,7,size=(3,3))

In [35]:
r

array([[2, 0, 2],
       [0, 3, 5],
       [1, 4, 0]])

In [40]:
r[:]

array([[2, 0, 2],
       [0, 3, 5],
       [1, 4, 0]])

In [41]:
r[:5]

array([[2, 0, 2],
       [0, 3, 5],
       [1, 4, 0]])

In [42]:
r[5:]

array([], shape=(0, 3), dtype=int32)

In [43]:
r[2:]

array([[1, 4, 0]])

In [44]:
r[4:7]

array([], shape=(0, 3), dtype=int32)

In [53]:
# import timeit
# r[::2]
# st=start
# print(timeit.default_timer()-st)

In [54]:
M=np.ones(3,3)
M
print("MATRIX:\n"+M)

TypeError: data type not understood

# pandas
**UseCases *
- Data cleaning
- Data Transformation
- Data Analysis

**Notations *
- series
- DataFrames



In [57]:
import pandas as pd
internal1={"s1":21,"s2":18,"s3":24}
internal1=pd.Series(internal1)
internal1

s1    21
s2    18
s3    24
dtype: int64

In [59]:
import pandas as pd
internal2={"s1":21,"s2":18,"s3":24}
internal2=pd.Series(internal2)
internal2

s1    21
s2    18
s3    24
dtype: int64

In [61]:
import pandas as pd
final={"internal1":internal1,"internal2":internal2}
final=pd.DataFrame(final)
final

internal1  internal2
s1         21         21
s2         18         18
s3         24         24

In [63]:
import pandas as pd
final={"internal1":internal1,"internal2":internal2}
final=pd.DataFrame(final)
final['internal1']

s1    21
s2    18
s3    24
Name: internal1, dtype: int64

In [64]:
final.columns

Index(['internal1', 'internal2'], dtype='object')

In [65]:
final.values

array([[21, 21],
       [18, 18],
       [24, 24]], dtype=int64)

In [66]:
final.values[2][0]

24

In [72]:
for row in final.values:
    print("internal1",row[0])

internal1 21
internal1 18
internal1 24


In [76]:
final.loc["s4"]=[1,1]
final

internal1  internal2
s1         21         21
s2         18         18
s3         24         24
3          15         18
s4          1          1

In [77]:
final.drop(3)

internal1  internal2
s1         21         21
s2         18         18
s3         24         24
s4          1          1

In [78]:
final

internal1  internal2
s1         21         21
s2         18         18
s3         24         24
3          15         18
s4          1          1

In [79]:
final=final.drop(3)

In [80]:
final

internal1  internal2
s1         21         21
s2         18         18
s3         24         24
s4          1          1

In [81]:
final.values[2]=[12,25]

In [82]:
final

internal1  internal2
s1         21         21
s2         18         18
s3         12         25
s4          1          1

In [88]:
#reading csv file data
import pandas as pd
filepath="Income.csv"
incomedataf=pd.read_csv(filepath)
incomedataf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [89]:
# extra income of all states in 2013
# california:57528
for row in incomedataf.values:
    print(row[1],':',row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [93]:
# average income of arizona
sum=0
for i in range(2,11):
    sum+=incomedataf.values[2][i]
sum//len(incomedataf.values[2][2:])
    

47214

In [98]:
#average income of all states in year 2012
sum=0
for i in incomedataf.values:
    sum+=row[-2]
sum/len(incomedataf.values)

57020.0

In [5]:
a=["Url","Url","Url","url1","url1","url2"]
for i in a:
    print(i)
    print(max(a))
    #for j in range(max(a.count(i)),min(a.count(i)),-2):
    #    print(a[j])

Url


TypeError: 'int' object is not iterable